name: spoolman-importer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - requests
  - python-dotenv
  - pytest
  - pytest-mock
  - pytest-cov
  - flake8
  - black
  - pip
  - pip:
    - pypdf>=3.0.0
    - openai
